try:
    raise Exception('foo!')
except:
    print("accepted")
